name: core_kit
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl:
  flutter_html:
  flutter_auto_size_text:
  skeletonizer:
  file_picker:
  flutter_country_state:
  flutter_svg:
  cached_network_image:
  image_picker:
  permission_handler:
  dio:
  intl_phone_field_v2:
  # another_flushbar:
  share_plus:
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
 

